name: Single CI Pipeline

on:
    workflow_dispatch:
        inputs:
            app:
              description:  "The Application choices A, B or C"
              required: true
              default: "A"
              
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

    pre-build:
        uses:  ./.github/workflows/pre-build.yml
        with: 
            app: ${{ inputs.app }}
            runner: ubuntu-latest

    build:
        needs: pre-build
        uses: ./.github/workflows/build.yml
        with: 
            app: ${{ inputs.app }}
            runner: ubuntu-latest

    test:
        needs: build
        uses: ./.github/workflows/test.yml
        with: 
            app: ${{ inputs.app }}
            runner: ubuntu-latest
        
    lint:
        needs: build
        uses: ./.github/workflows/lint.yml
        with: 
            app: ${{ inputs.app }}
            runner: ubuntu-latest