name: Lint Workflow

on:
    workflow_call:
        inputs:
            app:
                required: true
                type: string
                description: Choice of Application A, B or C


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Linting App A
              run: |
                echo "Lint App A"
                npm run lint
              working-directory: ${{ github.workspace }}/react-app
              if: ${{ inputs.app == 'A' }}

            - name: Linting App B
              run: |
                echo "Lint App B"
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
              working-directory: ${{ github.workspace }}/pyproject
              if: ${{ inputs.app == 'B'  }}

            - name: Linting App C
              run: |
               echo "Lint App A"
               pwd
               echo "Testing completed"
              working-directory: ${{ github.workspace }}/java-maven
              if: ${{ inputs.app == 'C'   }}
