name: Test Workflow

on:
    workflow_call:
        inputs:
            app:
                required: true
                type: string
                description: Choice of Application A, B or C

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Testing  App A
              run: |
                npm test
              working-directory: ${{ github.workspace }}/react-app
              if: ${{ inputs.app == 'A' }}

            - name: Testing  App B
              run: |
               echo "Test App B"
               pwd
               python -m pytest addition.py
               echo "Testing competed"
              working-directory: ${{ github.workspace }}/pyproject/src
              if: ${{ inputs.app == 'B'  }}

            - name: Testing  App C
              run: |
               pwd
               echo "Testing completed"
              working-directory: ${{ github.workspace }}/java-maven
              if: ${{ inputs.app == 'C'   }}

   